kind: pipeline
name: build

steps:
  - name: restore build cache
    image: meltwater/drone-cache
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "volume"
      archive_format: "gzip"
      mount:
        - 'node_modules'
        - '.next'
    volumes:
    - name: cache
      path: /tmp/cache

  - name: build app
    image: node:current-alpine
    commands:
      - npm install
      - npm run build

  - name: rebuild build cache
    image: meltwater/drone-cache
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "volume"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - 'node_modules'
        - '.next'
    volumes:
    - name: cache
      path: /tmp/cache


volumes:
  - name: cache
    host:
      path: /tmp


trigger:
  event: [push, custom]
  branch: [drone-ci]

---
kind: pipeline
name: deploy

steps:
  - name: docker login
    image: automagistre/docker:stable
    environment:
      USERNAME:
        from_secret: cynicsoft_registry_username
      PASSWORD:
        from_secret: cynicsoft_registry_password
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock
      - name: docker-config
        path: /root/.docker
    commands:
      - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin "docker-hub.cynicsoft.net"

  - name: publish docker image
    image: automagistre/docker:stable
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock
      - name: docker-config
        path: /root/.docker
    commands:
      - export IMAGE_TAG=docker-hub.cynicsoft.net/homepage:$DRONE_COMMIT_BRANCH
      - docker image build --tag $IMAGE_TAG .
      - docker push $IMAGE_TAG


volumes:
  - name: docker.sock
    host:
      path: /var/run/docker.sock
  - name: cache
    host:
      path: /tmp
  - name: docker-config
    temp: {}


trigger:
  event: [push, custom]
  branch: [drone-ci]

---
kind: pipeline
name: trigger repo

steps:
  - name: trigger repo
    image: plugins/downstream
    settings:
      server: http://drone-server
      token:
        from_secret: drone_token
      repositories: [jon-chen-configs/homepage-stack]


trigger:
  event: [push, custom]
  branch: [drone-ci]