kind: pipeline
name: default

steps:
  - name: restore build cache
    image: meltwater/drone-cache
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "volume"
      archive_format: "gzip"
      mount:
        - 'node_modules'
    volumes:
    - name: cache
      path: /tmp/cache

  - name: build app
    image: node:current-alpine
    commands:
      - npm install
      - npm run build

  - name: rebuild build cache
    image: meltwater/drone-cache
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "volume"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - 'node_modules'
    volumes:
    - name: cache
      path: /tmp/cache

  # Dockerfile doesn't build in docker plugin
  # - name: publish docker image
  #   image: plugins/docker
  #   settings:
  #     registry: docker-hub.cynicsoft.net
  #     username:
  #       from_secret: cynicsoft_registry_username
  #     password:
  #       from_secret: cynicsoft_registry_password
  #     repo: jon-chen/homepage
  #     tags: $DRONE_BRANCH
  - name: publish docker image
    image: automagistre/docker:stable
    environment:
      IMAGE_TAG: docker-hub.cynicsoft.net/homepage:$DRONE_REPO_BRANCH
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock
    commands:
      - docker image build --tag $IMAGE_TAG .
      - docker push $IMAGE_TAG

  - name: trigger repo
    image: plugins/downstream
    settings:
      server: http://drone-server
      token:
        from_secret: drone_token
      repositories: [jon-chen-configs/homepage-stack]

volumes:
  - name: docker.sock
    host:
      path: /var/run/docker.sock
  - name: cache
    host:
      path: /tmp


trigger:
  event: [push, custom]
  branch: [drone-ci]